from .notes27_jan_delete_test import Notes27JanDeleteTestCase
from .notes27_jan_update_test import Notes27JanUpdateTestCase
from .notes27_jan_detail_test import Notes27JanDetailTestCase
from .notes27_jan_create_test import Notes27JanCreateTestCase
from .notes27_jan_list_test import Notes27JanListTestCase
