from .notes27_jan_delete import Notes27JanDeleteView
from .notes27_jan_update import Notes27JanUpdateView
from .notes27_jan_detail import Notes27JanDetailView
from .notes27_jan_create import Notes27JanCreateView
from .notes27_jan_list import Notes27JanListView
